// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeKVD1L6TUNsI5BstmE7ywinDiTkwHpxo',
    appId: '1:243906736454:web:c2e8e63a5242f1c67ef547',
    messagingSenderId: '243906736454',
    projectId: 'audioscribe-project',
    authDomain: 'audioscribe-project.firebaseapp.com',
    storageBucket: 'audioscribe-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc23Fw5jgTD8gUpxK9dc45sbfotJn_J30',
    appId: '1:243906736454:android:99f96ae516c2280c7ef547',
    messagingSenderId: '243906736454',
    projectId: 'audioscribe-project',
    storageBucket: 'audioscribe-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdYlI3PWhxC7Ii3ppijKQONVR_YWIdVZE',
    appId: '1:243906736454:ios:417068986ac7e8bc7ef547',
    messagingSenderId: '243906736454',
    projectId: 'audioscribe-project',
    storageBucket: 'audioscribe-project.appspot.com',
    iosBundleId: 'com.example.audioscribe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdYlI3PWhxC7Ii3ppijKQONVR_YWIdVZE',
    appId: '1:243906736454:ios:e8ce058f4a24a9b67ef547',
    messagingSenderId: '243906736454',
    projectId: 'audioscribe-project',
    storageBucket: 'audioscribe-project.appspot.com',
    iosBundleId: 'com.example.audioscribe.RunnerTests',
  );
}
